 export type NFTObject = {
    _id: string;
    NFTPoolAddress: string;
    NFTPoolType: string;
    NFTMaxCap: number;
    StartTime: number;
    EndTime: number;
    UnlockTime: number;
    Tiers: number;
    LPTokenName: string;
    LPTokenAddress: string;
    AmounttoLock: string;
    NFTName: string;
    NFTArtist: string;
    NFTImageURL: string;
    ProjectTitle: string;
    ProjectFacebook: string;
    ProjectInsta: string;
    ProjectTwitter: string;
    ProjectMedium: string;
    ProjectTelegram: string;
    ProjectYoutube: string;
    Purchased:string;
    Participants:string;
    FilledPercentage:number;
    ProjectDiscord: string;
    AboutProject: string;
    ProjectShortDesc: string;
    ProjectStatus: string;
    __v: number;
  };
  